#!/bin/bash
VER=1.6
####
#### Copyright (C) 2019  wuseman <wuseman@nr1.nu> - All Rights Reserved
#### Last revised 14012019
#### GNU GENERAL PUBLIC LICENSE
#### Usage: ./wbruter -[option]
####


if [[ -z $1 ]]; then source .scripts/wbruter-help.sh; help;exit;fi


while getopts ":abghGArzf" getopt; do
case $getopt in
a)
source .scripts/android-cli.sh
source .scripts/android-cli6.sh
if [[ -z $2 ]]; then
      echo "Error: You must specify atleast one argument of 4 or 6 digits (./wbruter -a 4)"
fi

case $2 in
      "4") androidpinattack ;;
      "6") androidpinattack6 ;;
esac 
;;

A)
if [[ -z $2 ]]; then
      echo "Error: You must specify atleast one argument of 4 or 6 digits (./wbruter -A 4)"
      echo "You might wanna try to use -a instead of A for guarantee to break the pin"
fi

case $2 in
      "4") source .scripts/wbruter-android.sh; android_gui_pin_attack ;;
      "6") source .scripts/wbruter-android6.sh; android_gui_pin6_attack;;
esac ;;
h) source .scripts/wbruter-help.sh; help ;;
f) source .scripts/wbruter-ftp.sh; ftp_attack ;;
G) source .scripts/wbruter-gpg.sh; gpg_attack ;;
g) source .scripts/wbruter-gmail.sh; gmail_attack ;;
r) source .scripts/wbruter-rar.sh;rar_attack  ;;
z) source .scripts/wbruter-zip.sh; zip_attack ;;
esac
done


